/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const SandboxLazyImport = createFileRoute('/sandbox')()
const ResumeLazyImport = createFileRoute('/resume')()
const FormLazyImport = createFileRoute('/form')()

// Create/Update Routes

const SandboxLazyRoute = SandboxLazyImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sandbox.lazy').then((d) => d.Route))

const ResumeLazyRoute = ResumeLazyImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/resume.lazy').then((d) => d.Route))

const FormLazyRoute = FormLazyImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeLazyImport
      parentRoute: typeof rootRoute
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form': typeof FormLazyRoute
  '/resume': typeof ResumeLazyRoute
  '/sandbox': typeof SandboxLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form': typeof FormLazyRoute
  '/resume': typeof ResumeLazyRoute
  '/sandbox': typeof SandboxLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/form': typeof FormLazyRoute
  '/resume': typeof ResumeLazyRoute
  '/sandbox': typeof SandboxLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form' | '/resume' | '/sandbox'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form' | '/resume' | '/sandbox'
  id: '__root__' | '/' | '/form' | '/resume' | '/sandbox'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormLazyRoute: typeof FormLazyRoute
  ResumeLazyRoute: typeof ResumeLazyRoute
  SandboxLazyRoute: typeof SandboxLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormLazyRoute: FormLazyRoute,
  ResumeLazyRoute: ResumeLazyRoute,
  SandboxLazyRoute: SandboxLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/form",
        "/resume",
        "/sandbox"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/form": {
      "filePath": "form.lazy.jsx"
    },
    "/resume": {
      "filePath": "resume.lazy.jsx"
    },
    "/sandbox": {
      "filePath": "sandbox.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
